In [ ]:
# 1. Write a python Program for Bidirectional Associative Memory with two pairs of vectors.

In [2]:
import numpy as np

# Define two sets of patterns: Set A and Set B
# Set A: Input Patterns
x1 = np.array([1, 1, 1, 1, 1, 1]).reshape(6, 1)
x2 = np.array([-1, -1, -1, -1, -1, -1]).reshape(6, 1)

# Set B: Target Patterns
y1 = np.array([1, 1]).reshape(2, 1)
y2 = np.array([-1, -1]).reshape(2, 1)

# Calculate the weight matrices: W and W_T
W = np.dot(x1, y1.T) + np.dot(x2, y2.T)
W_T = np.dot(y1, x1.T) + np.dot(y2, x2.T)

# Testing Phase
# Test for Input Patterns: Set A
print("Testing for input patterns: Set A")
def testInputs(x, weight):
    # Compute the output pattern
    y = np.dot(weight, x)
    y[y < 0] = -1
    y[y >= 0] = 1
    return y

def testTargets(y, weight):
    # Compute the output pattern
    x = np.dot(weight, y)
    x[x <= 0] = -1
    x[x > 0] = 1
    return x

print("\nOutput of input pattern 1:")
print(testInputs(x1, W_T))
print("\nOutput of input pattern 2:")
print(testInputs(x2, W_T))

# Test for Target Patterns: Set B
print("\nTesting for target patterns: Set B")

print("\nOutput of target pattern 1:")
print(testTargets(y1, W))
print("\nOutput of target pattern 2:")
print(testTargets(y2, W))


Testing for input patterns: Set A

Output of input pattern 1:
[[1]
 [1]]

Output of input pattern 2:
[[-1]
 [-1]]

Testing for target patterns: Set B

Output of target pattern 1:
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]

Output of target pattern 2:
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]


In [4]:
# code2

In [3]:
# Define two pairs of vectors
X1 = np.array([1, 1, 1, 0, 0])
X2 = np.array([0, 0, 1, 1, 1])
Y1 = np.array([1, 0, 0])
Y2 = np.array([0, 1, 0])

In [6]:
# Define the weight matrix
W = np.zeros((len(X1), len(Y1)))
for i in range(len(X1)):
    for j in range(len(Y1)):
        W[i][j] = X1[i] * Y1[j] + X2[i] * Y2[j]

In [8]:
#Define the BAM function
def BAM(input_vector):
    output_vector = np.zeros(len(Y1))
    for j in range(len(Y1)):
        sum = 0
        for i in range(len(X1)):
            sum += input_vector[i] * W[i][j]
            output_vector[j] = sum
            return output_vector

In [10]:
input_vector = X1
output_vector = BAM(input_vector)
print("Input vector:", input_vector)
print("Output vector:", output_vector)

Input vector: [1 1 1 0 0]
Output vector: [1. 0. 0.]
